<%@ Page Title="" Language="C#" MasterPageFile="~/SiteLayout.Master" AutoEventWireup="true" CodeBehind="GioiThieu.aspx.cs" Inherits="BaiDuAn.GioiThieu" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <div class="row"><div class="col-md-8"><div class="left"><h1>GIỚI THIỆU </h1><p><strong>Max Moto Sài Gòn là một trong những đại lý chính hãng Kawasaki đầu tiên tại Việt Nam, với cơ sở hạ tầng theo tiêu chuẩn 3S của hãng Kawasaki, bán lẻ tất cả các sản phẩm Kawasaki chính hãng.Tất cả sản phẩm đều là Phiên bản Châu Âu, có ABS và bảo hành chính hãng, phụ tùng thay thế đầy đủ, đến với MAX Moto Sài Gòn quý khách sẽ thật sự an tâm với uy tín và cách phục vụ chu đáo của chúng tôi.</strong></p></div></div><div class="col-md-4"><div class="right"><p> <noscript><img src="https://maxmoto.com.vn/wp-content/uploads/2019/12/7-9.jpg" class="img-fluid" width="100%" alt="mô tô 1"></noscript><img src="https://maxmoto.com.vn/wp-content/uploads/2019/12/7-9.jpg" data-src="https://maxmoto.com.vn/wp-content/uploads/2019/12/7-9.jpg" class="img-fluid ls-is-cached lazyloaded" width="100%" alt="mô tô 1"></p><p> <noscript><img src="https://maxmoto.com.vn/wp-content/uploads/2019/12/3-6.jpg" class="img-fluid" width="100%" alt="mô tô 2"></noscript></p><p> <noscript><img src="https://maxmoto.com.vn/wp-content/uploads/2019/12/4-3.jpg" class="img-fluid" width="100%" alt="mô tô 3"></noscript></p></div></div></div>
    <div class="info-about padt padb"><div class="container"><div class="content sans"><div class="row"><div class="col-md-8"><div class="left">
        <p>Hỗ trợ tối đa các thủ tục mua Moto kawasaki trả góp, thủ tục đơn giản không thế chấp, giao hàng nhanh chóng, Dịch vụ đăng ký chủ quyền xe cho các trường hợp đặt biệt, các dịch vụ hỗ trợ học thi lấy bằng lái xe A2 theo đúng quy định của nhà nước nhanh chóng tiết kiện thời gian và chi phí cho khách hàng.</p>
        <div class="showroom"><h3 class="sans-bold">Hệ thống showroom</h3><div class="row"><div class="col-md-6"><div class="place"><ul><li>1. 
 TPHCM : 353 Phạm Hùng, Bình Chánh</li><li>2. 
 Hà Nội : 91 Âu Cơ, Tây Hồ</li></ul><p>Bán hàng hỗ trợ giao xe toàn quốc</p></div></div><div class="col-md-6"><div class="hotline"><ul><li><i class="fa fa-phone"></i> HOTLINE:</li><li>(028) 62 868 555</li><li>(028) 22 32 6666</li><li>(028) 22 33 6666</li><li>(024) 3223 2555</li></ul></div></div></div></div></div></div><div class="col-md-4"><div class="right"> <noscript><img src="https://maxmoto.com.vn/wp-content/uploads/2019/11/4-1.jpg" class="img-fluid" width="100%" alt="Giới thiệu">

                                                                                                                                                                                                                                                                                                                                                                          </noscript><img src="https://maxmoto.com.vn/wp-content/uploads/2019/11/4-1.jpg" data-src="https://maxmoto.com.vn/wp-content/uploads/2019/11/4-1.jpg" class="img-fluid lazyloaded" width="100%" alt="Giới thiệu"></div></div></div></div></div></div>
 </asp:Content>
